services:

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

  node-app:
    build: ./node-app
    container_name: node-app
    ports:
      - "3000:3000"

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: laboratorio
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./volumes/pgadmin-data:/var/lib/pgadmin

  jupyter:
    image: jupyter/base-notebook
    container_name: jupyter-lab
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''

# --- NUEVOS SERVICIOS PARA EL LABORATORIO DE SISTEMAS OPERATIVOS ---
  postgres-lab:
    image: postgres:15-alpine
    container_name: postgres-lab-container
    environment:
      POSTGRES_USER: lab_user
      POSTGRES_PASSWORD: lab_password
      POSTGRES_DB: lab_os_db
    volumes:
      - postgres_lab_data:/var/lib/postgresql/data
      - ./services/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lab_internal_network
    deploy:
      resources:
        limits:
          cpus: '0.5'        # Restringe el uso a máximo la mitad de un núcleo de CPU
          memory: 256M       # Límite estricto de memoria RAM física

  nextjs-lab:
    build:
      context: ./services/nextjs-app
      dockerfile: Dockerfile
    container_name: nextjs-lab-container
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgres://lab_user:lab_password@postgres-lab:5432/lab_os_db
      NODE_ENV: production
    depends_on:
      - postgres-lab
    networks:
      - lab_internal_network
    deploy:
      resources:
        limits:
          cpus: '0.5'        # Restringe a la mitad de un núcleo de CPU
          memory: 300M       # Si Next.js excede esto, el sistema operativo actuará


  stress-ai:
    build:
      context: ./services/stress-ai
      dockerfile: Dockerfile
    container_name: stress-ai-lab
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 5G


networks:
  lab_internal_network:
    driver: bridge

volumes:
  postgres_lab_data:
    driver: local

